### ISSUE TITLE
When add listener in ListView or RecyclerView, a problem happened

### ISSUE THREAD

**Issue by brucetoo** [mrmans0n/smart-adapters#1]
When add listener in ListView or RecyclerView,we cannot show reveal effect in 5.0+ ,or selector effect in each item...u can see this problem in ur sample app

**Comment by mrmans0n** [comment]
The background in the custom views was not set. It's just a matter of adding:

``` xml
    android:background="?android:attr/selectableItemBackground"
```

to the background to have it. I will be updating the sample with it.
