### ISSUE TITLE
SmartAdapter is tied to needing mappings

### ISSUE THREAD

**Issue by soymonitus** [mrmans0n/smart-adapters#5]
It is stated in the README that you setting a map between model and view is not necessary when you pass your own implementation of BindableLayoutBuilder but it is not true:

1) getItemViewType crashes because 
        Object object = listItems.get(position);
        return mapper.position(object.getClass());
throws an exception when calling position, as it cannot find any mapping

But if I add some dummy mapping to bypass this exception the problem is then a different one: The different type of cells (views) are mixed when they are reused:
Consider your own example:
Adapter:
SmartAdapter.items(myObjectList)
    .map(Tweet.class, TweetView.class)
    .into(myListView);

BindableLayoutBuilder:
public class TweetBindableLayoutBuilder implements BindableLayoutBuilder {

```
@Override
public BindableLayout build(ViewGroup parent, Mapper mapper, Class aClass, Object item) {
    // parent = the parent, Mapper = object -> view mapper defined in the SmartAdapters invocation
    // aClass = current model (item) class, item = current object

    Tweet tweet = (Tweet) item;
    if (tweet.hasGallery()) {
        return new TweetGalleryView(parent.getContext());
    } else if (tweet.hasImage()) {
        return new TweetImageView(parent.getContext());
    } else if (tweet.hasEmbeds()) {
        return new TweetEmbedView(parent.getContext());
    } else {
        return new TweetView(parent.getContext());
    }
}
```

}

Then, inside the RecyclerView adapter method getItemViewType we have:
public int getItemViewType(int position) {
        if (listItems == null) {
            return 0;
        }
        Object object = listItems.get(position);
        return mapper.position(object.getClass());
}

As the mapper will get position 0 for the class Tweet, all the cells will be considered the same so the build method of the TweetBindableLayoutBuilder could not be called a TweetImageView is needed because it reused another one, which can be of any (undesired) type like TweetView or TweetGalleryView

**Comment by soymonitus** [comment]
My suggestion would be that the BindableLayoutBuilder has another method to specify the viewtype depending on the Item and position, something like:

public interface BindableLayoutBuilder<T, Q extends BindableLayout<T>> {
    Q build(@NonNull ViewGroup parent, @NonNull Mapper mapper, @NonNull Class aClass, T item);
    int viewType(@NonNull ViewGroup parent, @NonNull Mapper mapper, @NonNull Class aClass, T item);
}

**Comment by mrmans0n** [comment]
You are right, I will give this a thought when I come back from holidays
and have an actual computer to fix it. Good catch, I did not remember this
when I wrote that statement 😅

**Comment by soymonitus** [comment]
Buenísimas tus libs por cierto! Justo lo que andaba buscando (incluida la de location) :)
