### ISSUE TITLE
recyclerview ItemAnimator

### ISSUE THREAD

**Issue by DJafari** [mrmans0n/smart-adapters#7]
when i use custom itemAnimator, i must use `notifyItemInserted` and `notifyItemRemoved` instead of `notifyDataSetChanged` in adapter, in smart adapter how can do it ?

thanks

**Comment by mrmans0n** [comment]
Get the adapter (it is returned by default) and save it in a variable so you can access it later. In the adapter you can access all those functions by yourself I guess. 

Although I think you couldn't avoid it to call notifyDataSetChanged. I will flag this message so I remove those automatic calls for the next version of the library (or put them under a configurable flag so it is enabled by default but can be disabled).

**Comment by DJafari** [comment]
thanks, i will wait for it

**Comment by mrmans0n** [comment]
Now you can call `yourAdapter.setAutoDataSetChanged(false)` and do the notifyItemInserted and notifyItemRemoved you need by hand. It's live on version 1.1.2 of the library.
